name: Release action
# Call the reusable workflow release-solution-with-inputs.yml
# Release your solution to prod when you create a new release.

on:
  release:
      types: [created]        
permissions:
  contents: write
jobs:
  Release-solution-ALMLab:
    uses: ./.github/workflows/release-solution-to-prod-with-inputs.yml
    with:
      #You can specify the solution name here
      solution_name: ALMLab
      #Update your values here
      BUILD_ENVIRONMENT_URL: 'https://orga982f0ce.crm.dynamics.com/'
      PRODUCTION_ENVIRONMENT_URL: 'https://org0a6677d9.crm.dynamics.com/'
      CLIENT_ID: 'e7795377-ea5e-4126-b3c3-664c85f9b791'
      TENANT_ID: '25467c26-77bd-45e1-9df5-1fe15127245f'     
    secrets:
      envSecret: ${{ secrets.PowerPlatformSPN }}
